# Generated by Django 5.1.3 on 2024-11-10 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChannel",
            fields=[
                ("channel_id", models.UUIDField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("direct_message", models.BooleanField()),
                ("participants", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.UUIDField(primary_key=True, serialize=False)),
                ("sent_date", models.DateTimeField()),
                ("text", models.CharField(max_length=4096)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.groupchannel",
                    ),
                ),
            ],
        ),
    ]
