# Generated by Django 5.1.3 on 2024-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_rename_groupchannel_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
