# Generated by Django 5.1.3 on 2024-11-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0004_alter_channel_channel_id_alter_message_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
